data:
 train: "/well/clifton/projects/ukb_v2/derived/prot_final/train_imp_simple.csv"
 test: "/well/clifton/projects/ukb_v2/derived/prot_final/test_imp_simple.csv"
outputs:
 figures: "/well/clifton/users/ncu080/ad4mm/figures"
 outputs: "/well/clifton/users/ncu080/ad4mm/outputs"
scripts:
 cleaning: "/well/clifton/users/ncu080/UKB_Project/cleaning"
 processing: "/well/clifton/users/ncu080/UKB_Project/processing"
